const mongoose = require("mongoose");
const { UserSchema } = require("./_common-schema");

const RepoSchema = new mongoose.Schema(
  {
    id: { type: Number, required: true },
    node_id: { type: String, required: true },
    name: { type: String, required: true },
    full_name: { type: String, required: true },
    owner: { type: UserSchema, required: true },
    private: { type: Boolean, required: true },
    html_url: { type: String, required: true },
    description: { type: String, default: null },
    fork: { type: Boolean, required: true },
    url: { type: String },
    archive_url: { type: String, required: true },
    assignees_url: { type: String, required: true },
    blobs_url: { type: String, required: true },
    branches_url: { type: String, required: true },
    collaborators_url: { type: String, required: true },
    comments_url: { type: String, required: true },
    commits_url: { type: String, required: true },
    compare_url: { type: String, required: true },
    contents_url: { type: String, required: true },
    contributors_url: { type: String, required: true },
    deployments_url: { type: String, required: true },
    downloads_url: { type: String, required: true },
    events_url: { type: String, required: true },
    forks_url: { type: String, required: true },
    git_commits_url: { type: String, required: true },
    git_refs_url: { type: String, required: true },
    git_tags_url: { type: String, required: true },
    git_url: { type: String },
    issue_comment_url: { type: String, required: true },
    issue_events_url: { type: String, required: true },
    issues_url: { type: String, required: true },
    keys_url: { type: String, required: true },
    labels_url: { type: String, required: true },
    languages_url: { type: String, required: true },
    merges_url: { type: String, required: true },
    milestones_url: { type: String, required: true },
    notifications_url: { type: String, required: true },
    pulls_url: { type: String, required: true },
    releases_url: { type: String, required: true },
    ssh_url: { type: String },
    stargazers_url: { type: String, required: true },
    statuses_url: { type: String, required: true },
    subscribers_url: { type: String, required: true },
    subscription_url: { type: String, required: true },
    tags_url: { type: String, required: true },
    teams_url: { type: String, required: true },
    trees_url: { type: String, required: true },
    clone_url: { type: String },
    mirror_url: { type: String, default: null },
    hooks_url: { type: String, required: true },
    svn_url: { type: String },
    homepage: { type: String, default: null },
    language: { type: String, default: null },
    forks_count: { type: Number },
    stargazers_count: { type: Number },
    watchers_count: { type: Number },
    size: { type: Number },
    default_branch: { type: String },
    open_issues_count: { type: Number },
    is_template: { type: Boolean },
    topics: [{ type: String }],
    has_issues: { type: Boolean },
    has_projects: { type: Boolean },
    has_wiki: { type: Boolean },
    has_pages: { type: Boolean },
    has_downloads: { type: Boolean },
    has_discussions: { type: Boolean },
    archived: { type: Boolean },
    disabled: { type: Boolean },
    visibility: { type: String },
    pushed_at: { type: String, default: null },
    created_at: { type: String, default: null },
    updated_at: { type: String, default: null },
    permissions: {
      admin: { type: Boolean },
      maintain: { type: Boolean },
      push: { type: Boolean },
      triage: { type: Boolean },
      pull: { type: Boolean },
    },
    role_name: { type: String },
    temp_clone_token: { type: String },
    delete_branch_on_merge: { type: Boolean },
    subscribers_count: { type: Number },
    network_count: { type: Number },
    code_of_conduct: {
      key: { type: String },
      name: { type: String },
      url: { type: String },
      body: { type: String },
      html_url: { type: String, default: null },
    },
    license: {
      key: { type: String },
      name: { type: String },
      spdx_id: { type: String },
      url: { type: String },
      node_id: { type: String },
    },
    forks: { type: Number },
    open_issues: { type: Number },
    watchers: { type: Number },
    allow_forking: { type: Boolean },
    web_commit_signoff_required: { type: Boolean },
    security_and_analysis: {
      advanced_security: {
        status: { type: String, enum: ["enabled", "disabled"] },
      },
      code_security: {
        status: { type: String, enum: ["enabled", "disabled"] },
      },
      dependabot_security_updates: {
        status: { type: String, enum: ["enabled", "disabled"] },
      },
      secret_scanning: {
        status: { type: String, enum: ["enabled", "disabled"] },
      },
      secret_scanning_push_protection: {
        status: { type: String, enum: ["enabled", "disabled"] },
      },
      secret_scanning_non_provider_patterns: {
        status: { type: String, enum: ["enabled", "disabled"] },
      },
      secret_scanning_ai_detection: {
        status: { type: String, enum: ["enabled", "disabled"] },
      },
    },
    custom_properties: {
      type: mongoose.Schema.Types.Mixed,
      default: {},
    },
  },
  { strict: false },
);

module.exports = mongoose.model("GitHubRepo", RepoSchema, "github_repos");
